### ISSUE TITLE
Unenumerable supported property names are badly defined

### ISSUE THREAD

**Issue by nox** [heycam/webidl#79] opened 2015-12-22 09:08 UTC
It is not clear whether they should appear in the result of Object.getOwnPropertyNames. It should probably be clearly stated that they are to.

Cc @heycam

**Comment by annevk** [comment] 2016-02-16 12:37
Well, we should define this by defining PlatformObjectOwnPropertyKeys, as part of ES6 integration.

**Comment by annevk** [comment] 2017-08-10 14:46
Closing as duplicate of a more active issue: #400.

**Closed by annevk** 2017-08-10 14:46 UTC
Labels: editorial, ⌛⌛, ☕☕
